### ISSUE TITLE
wall 

### ISSUE THREAD

**Issue by maxill1** [normen/maxcube2#1]
hi i see you changed the way of reading wall thermostat since commit b2a8555297e25a1e2d42add2a22c6a967325ddb5

the new way breaks my WM readings:

-  setpoint 81 (should be 17) 
-  temp 2.2 (should be 27.8)

`{
    "rf_address": "18eb18",
    "initialized": true,
    "fromCmd": false,
    "error": false,
    "valid": true,
    "mode": "AUTO",
    "dst_active": true,
    "gateway_known": true,
    "panel_locked": false,
    "link_error": false,
    "battery_low": false,
    "valve": 4,
    "setpoint": 81,
    "temp": 2.2,
    "device_type": 3,
    "device_name": "Termostato a parete",
    "room_name": "Piano terra",
    "room_id": 1
}`

worked fine with my patch (https://github.com/ivesdebruycker/maxcube/pull/25), but i see for some don't.

Did you switched to this new way of reading because my fix didn't work for you?

please take a look at the issue on maxcube page https://github.com/ivesdebruycker/maxcube/issues/27

**Comment by normen** [comment]
Hi!

See this issue: https://github.com/normen/homebridge-platform-maxcube/issues/13

You seem to have one of the less wide spread wall thermostats.

Cheers,
Normen
