### ISSUE TITLE
Method to set the room temperature programmatically

### ISSUE THREAD

**Issue by skyup-str** [normen/maxcube2#10]
First of all - thanks for your work! I really appreciate it.

I'd like to read the current room temperature from an external sensor (not from the MAX!Wall-Thermostat)
and feed it to the heating thermostat. Is there any method to do so?

Thanks in advance for your help!

**Comment by normen** [comment]
No

**Comment by skyup-str** [comment]
"No" - because there is currently no method in this package to do it ...or "No" - because the api of the heating thermostat does not provide such a possibility?

**Comment by normen** [comment]
Both
