### ISSUE TITLE
self.initialised should not be changed in "on close event"

### ISSUE THREAD

**Issue by mikeS7** [normen/maxcube2#3]
https://github.com/normen/maxcube2/blob/714d260c8491f33db5f0e79673c8b0374a0f318f/maxcube.js#L33
self.initialised shouldn't be changed, we just close connection, but send function checks and reopen connection when needed
Such approach allows do not maintain permanent connection.

**Comment by normen** [comment]
This is called by the callback of the main connection, the user never calls it, I don't quite understand your point?

**Comment by mikeS7** [comment]
ok, I'll try to explain
I want to achieve non permanent connection to a cube behavior.
Function **send** calls **getConnection**, which calls **maxCubeLowLevel.connect**, which checks connection status and can return existing connection or create a new one. There is no reason to keep connection open.
All **MaxCube.prototype** functions call **checkInitialised** to check cube initialization status. **initialised** prpoperty sets to true during process "M" message to save metadata (device and room names etc.) at initial connection. **maxCubeLowLevel.on('closed',...)** sets the **initialised** property to false and after closing connection if you want to continue to work with the cube you should call **getConnection** before any other calls.
I think we can eliminate the **getConnection** call if just do not change **initialised** on close event. Cube answers with "M" response on any new connection so metadata will be updated.

**Comment by normen** [comment]
Ah, yeah. Now I know what you mean. Yeah, I guess the whole library could basically do with a rewrite, I kept most of the current ways it's working as is because it was supposed to be a continuation from the maxcube library. The whole "checkInitialized" thing looks like a bad workaround anyway.

**Comment by mikeS7** [comment]
I think `self.initialised = false;` in **on "closed"**  should be deleted, it will not change current behavior.

**Comment by normen** [comment]
Sure it will, you'll be able to reconnect, that didn't work in the original maxcube library :)
