### ISSUE TITLE
Month has off by one when setting vacation mode (Jan=00, ... Dec=11)

### ISSUE THREAD

**Issue by rbm78bln** [normen/maxcube2#5]
When setting vacation mode the devices show a number of the month-1, i.e.
2019-01-05 results in 05.00. in the display, 2019-02-05 results in 05.01. etc.

In _maxcube-commandfactory.js_ I have replaced line 24 to fix it by:
**`var month_until = padLeft((momentDate.get('month')+1).toString(2), 4);`** 

Hope this is the right place to fix it :-)

Querying the MAX!Cube gave me the correct results already.

**Comment by normen** [comment]
Okay.. Next time I touch the code will be for the next main release with (probably) a lot of changes, if you send a PR I will add this to the current master though.

**Comment by rbm78bln** [comment]
Created pull request #11 to fix it O:-)

**Comment by normen** [comment]
Added in 2.2.3
