### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by holgerpieta** [normen/maxcube2#8]
If the cube doesn't answer (e.g. disconnected from network), commands just go straight into nirvana.
The command is send and the promise is created for receiving data, but if no data is received, the promise is never resolved and just hangs around indefinitely.

It would be nice to have a timeout option that rejects the promise (and maybe emits some sort or error event) after a while.
net.socket supports a timeout, so probably that can be used.

**Comment by normen** [comment]
Sure, PR is welcome.

**Comment by holgerpieta** [comment]
I won't be able to help for about three weeks, so only merge and publish it before then if you're willing to deal with potential problems. I tested it on my system, but nowhere else.

**Comment by normen** [comment]
Yeah, issues will end up here :) The library was never pretty.
